name: Build Kivy APK with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Kivy Buildozer Docker image
        run: docker pull kivy/buildozer

      - name: Build APK using Dockerized Buildozer
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/app \
            -w /home/user/app \
            kivy/buildozer buildozer android debug

      - name: List APK files for debugging
        run: ls -l bin || echo "bin/ folder missing"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: kivy-apk
          path: bin/*.apk
