name: Build Kivy APK (No Artifact Upload Action)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04  # Or 24.04 if you must

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull Kali Docker image
      run: docker pull kalilinux/kali-rolling

         docker run --rm \
           -v ${{ github.workspace }}:/app \
          -w /app \
          kalilinux/kali-rolling /bin/bash -c "
            apt-get update &&
            apt-get install -y python3-pip git zip openjdk-17-jdk wget unzip curl libffi-dev libssl-dev libjpeg-dev zlib1g-dev build-essential ccache \
            && pip3 install --upgrade pip \
            && pip3 install cython virtualenv buildozer \
            && buildozer android debug
          "

          "

    - name: Zip APK manually
      run: |
        mkdir -p output
        zip -j output/kivy_apk_build.zip bin/*.apk
