name: Build Python APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libncurses5 \
            libstdc++6 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            openjdk-11-jdk \
            unzip \
            curl \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libgstreamer1.0 \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-tools

          pip install --upgrade pip setuptools wheel
          pip install cython virtualenv
          pip install buildozer

      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: python-app-apk
          path: bin/*.apk
