name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            libncurses5 \
            libstdc++6 \
            zlib1g \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libjpeg-dev

      - name: Install Buildozer & dependencies
        run: |
          pip install --upgrade pip
          pip install cython virtualenv
          pip install buildozer

      - name: Accept Android SDK licenses
        run: yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build APK
        run: buildozer android debug

      # OPTIONAL: Upload APK (currently commented due to GitHub bug)
      # - name: Upload APK
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: kivy-apk
      #     path: bin/*.apk
