name: Build Kivy APK

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            libncurses5 \
            libstdc++6 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            curl \
            libjpeg-dev

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Set environment variables for SDK/NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          echo "sdk.dir=$HOME/.buildozer/android/platform/android-sdk" > $GITHUB_ENV
          echo "ndk.dir=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Download and setup Android SDK & NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform

          # Download SDK
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip sdk-tools.zip -d android-sdk
          yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=${HOME}/.buildozer/android/platform/android-sdk --licenses
          android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=${HOME}/.buildozer/android/platform/android-sdk \
            "platform-tools" "platforms;android-31" "build-tools;31.0.0"

          # Download NDK
          curl -o ndk.zip https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip ndk.zip
          mv android-ndk-r25b android-ndk-r25b

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
