name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
            sudo apt-get update
            sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            openjdk-8-jdk \
            python3-dev \
            libssl-dev \
            libffi-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
    
        pip install --upgrade pip
        pip install buildozer cython virtualenv python-for-android setuptools

    - name: Initialize buildozer
      run: |
      
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mykivyapp-debug.apk
        path: bin/*.apk
