name: Build Kivy APK

on:
  push:
    branches: [ "main" ] # Or your main development branch
  pull_request:
    branches: [ "main" ]

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Using the latest version

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Or your preferred Python version

    - name: Install Dependencies
      run: |
        ls -l # Add this to list files and directories in the current workspace
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install your project's dependencies
        pip install kivy[full] # Install the full Kivy package
        pip install python-for-android # Install the build tool

    - name: Configure Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          pkg-config \
          zip \
          openjdk-17-jdk-headless # Or a compatible JDK

    - name: Build APK
      run: |
        python -m pythonforandroid.toolchain create \
          --requirements python3,kivy,your_other_dependencies \
          --name "YourAppName" \
          --package "com.yourdomain.yourappname" \
          --version 1.0 \
          --arch arm64-v8a \
          --arch armeabi-v7a \
          --copy-libs \
          --local-recipes your_local_recipes_directory # Optional: If you have local recipes
        mv bin/YourAppName-*-release.apk your_app_name.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app-apk
        path: your_app_name.apk
