name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04  # 👈 safer, stable runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer

      - name: Accept Android SDK licenses
        run: yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses || true

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3.1.3  # 👈 pin to working version
        with:
          name: kivy-apk
          path: bin/*.apk
