name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Kivy APK
        uses: ./.github/actions/kivy-to-apk
        with:
          work-dir: '.'  # or your subfolder if needed
