name: Build APK for Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev python3-pip build-essential git
          pip install --upgrade pip
          pip install kivy buildozer

      - name: Install Android dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
          sudo apt-get install -y unzip
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y zlib1g-dev
          sudo apt-get install -y libncurses5-dev  # Use libncurses5-dev instead



      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
