name: Build Kivy APK

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger when there's a PR to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can use 'macos-latest' if you're targeting macOS or 'windows-latest' for Windows

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            python3-pip \
            python3-setuptools \
            libjpeg-dev \
            zlib1g-dev \
            libgdk-pixbuf2.0-dev \
            libwebkit2gtk-4.0-dev \
            libglu1-mesa \
            libosmesa6-dev \
            libgl1-mesa-glx

      - name: Install Android SDK & NDK
        run: |
          sudo apt-get install -y unzip curl
          curl -s https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o sdk-tools.zip
          unzip sdk-tools.zip -d $HOME/android-sdk
          yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
          $HOME/android-sdk/tools/bin/sdkmanager --update
          $HOME/android-sdk/tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Install Buildozer & Kivy dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install kivy buildozer cython

      - name: Build APK with Buildozer
        run: |
          # Initialize buildozer if not done already
          buildozer init
          buildozer -v android debug  # Change 'debug' to 'release' for production build

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: /path/to/your/project/bin/*.apk  # Adjust the path to where your APK is generated
