name: Build Kivy APK on Ubuntu 22.04 with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04  # More stable than 24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull Kali Linux Docker image
      run: docker pull kalilinux/kali-rolling

    - name: Build APK inside Kali Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          kalilinux/kali-rolling /bin/bash -c "
            apt-get update &&
            apt-get install -y python3-pip git zip openjdk-17-jdk wget unzip curl libncurses5 build-essential ccache \
              libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
              && pip3 install --upgrade pip \
              && pip3 install cython virtualenv buildozer \
              && buildozer android debug
          "

    - name: Upload generated APK
      uses: actions/upload-artifact@v3.1.2  # Stable and tested version
      with:
        name: kivy-apk
        path: ./bin/*.apk
